name: CIpipeline

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout_code
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: insall dependencies
        run: npm install

      - name: run test
        run: npm test 
